apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    webhook: enabled
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80